config/routes.rb
JumacV2::Application.routes.draw do

    controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users, :except => [:show]

  get 'users/email_verification/:id' => 'users#email_verification', :as => :verify_email

  resources :roles, :except => [:show]
  resources :gun_categories, :except => [:show], :path => 'guncategories'
  resources :gun_calibers, :except => [:show], :path => 'guncalibers'
  resources :gun_finishes, :except => [:show], :path => 'gunfinishes'
  resources :gun_manufacturers, :except => [:show], :path => 'gunmanufacturers'
  resources :guns

  get "home/index"
  get "home/about"

  

  root :to => 'home#index'

end

app/models/gun.rb
class Gun < ActiveRecord::Base
	validates :model_name, :presence => true, :length => {:minimum => 3}, :uniqueness => true

	belongs_to :gun_category
	belongs_to :gun_manufacturer

	has_many :gun_available_calibers, :dependent => :destroy
	accepts_nested_attributes_for :gun_available_calibers

	has_many :gun_available_finishes, :dependent => :destroy
	has_many :gun_finishes, through: :gun_available_finishes	
	accepts_nested_attributes_for :gun_finishes
 
	
end

app/models/gun_available_finish.rb
class GunAvailableFinish < ActiveRecord::Base
	belongs_to :gun
	belongs_to :gun_finish
end

app/models/gun_caliber.rb
class GunCaliber < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }

	has_many :gun_available_calibers, :dependent => :destroy
	accepts_nested_attributes_for :gun_available_calibers
end

app/models/gun_category.rb
class GunCategory < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }

	has_many :guns
end

app/models/gun_finish.rb
class GunFinish < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }

	has_many :gun_available_finishes, :dependent => :destroy
end

app/models/gun_manufacturer.rb
class GunManufacturer < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }
	
	has_many :guns
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250 }
	validates :description, :length => { :maximum => 250 }

	has_many :user_roles, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :presence => true, :length => {:minimum => 3}, :uniqueness => true
	validates :email, :presence => true, :uniqueness => true
	validate :email_regex
 
	has_secure_password

	has_one :user_profile, :dependent => :destroy
	accepts_nested_attributes_for :user_profile

	has_many :user_roles, :dependent => :destroy
	has_many :roles, through: :user_roles
	accepts_nested_attributes_for :roles

	def email_regex
    if email.present? and not email.match(/^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i)
      errors.add :email, "This is not a valid email format"
    end

    def is_in_role(rolename)
    	
    end
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user	
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/controllers/gun_manufacturers_controller.rb
class GunManufacturersController < ApplicationController
  def index
    gun_manufacturer_all
  end

  def new
    @gunmanufacturer = GunManufacturer.new
  end

  def create
    @gunmanufacturer = GunManufacturer.new(gun_manufacturer_params)
    if @gunmanufacturer.save 
      redirect_to gun_manufacturers_path, :notice => "Manufacturer #{@gunmanufacturer.name} was created successfully."
    else
      render 'new'
    end
  end

  def edit
    @gunmanufacturer = GunManufacturer.find(params[:id])
  end

  def update
    @gunmanufacturer = GunManufacturer.find(params[:id])
    if @gunmanufacturer.update_attributes(gun_manufacturer_params)
      redirect_to gun_manufacturers_path, :notice => "Manufacturer #{@gunmanufacturer.name} was updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @gunmanufacturer = GunManufacturer.find(params[:id])
    @gunmanufacturer.destroy
    redirect_to gun_manufacturers_path, :notice => "Manufacturer #{@gunmanufacturer.name} was deleted successfully."
  end

  private 
  def gun_manufacturer_params
    params.require(:gun_manufacturer).permit(:name, :description)
  end
  def gun_manufacturer_all
    @gunmanufacturers = GunManufacturer.all
  end
end

app/controllers/guns_controller.rb
class GunsController < ApplicationController
  before_action :set_gun, only: [:edit, :update, :destroy]
  before_action :get_all_calibers, only: [:new, :edit]
  before_action :get_all_finishes, only: [:new, :edit]
  before_action :get_all_category, only: [:new, :edit]
  before_action :get_all_manufacturer, only: [:new, :edit]

  def index
    @guns = Gun.all
  end

  def new
    @gun = Gun.new
    # @gun.gun_available_calibers.build 
    @guncalibers = GunCaliber.all
    @guncalibers.each do |gc| 
      @gun.gun_available_calibers.find_or_create_by_gun_caliber_id(:gun_caliber_id => gc.id) {|u| u.is_available}
    end
    @gun.gun_finishes.build 
  end

  def create
    @gun = Gun.new(gun_params)    
    if @gun.save
      redirect_to guns_path, :notice => "Gun #{@gun.model_name} was created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  private
  def set_gun
    @gun = Gun.include(:gun_calibers, :gun_finishes).find(params[:id])
  end

  def gun_params
    params.require(:gun).permit(:model_name, :short_desc, :long_desc, :gun_category_id, :gun_manufacturer_id,       
      :gun_finish_ids, 
      :gun_available_calibers_attributes => [:id, :gun_caliber_id, :round_capacity, :is_available] 
      )
  end

  def get_all_calibers
    @guncalibers = GunCaliber.all
  end

  def get_all_finishes 
    @gunfinishes = GunFinish.all
  end

  def get_all_category
    @guncategory = GunCategory.all
  end

  def get_all_manufacturer
    @gunmanufacturer = GunManufacturer.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gun_caliber_helper.rb
module GunCaliberHelper
end

app/helpers/gun_category_helper.rb
module GunCategoryHelper
end

app/helpers/gun_finishes_helper.rb
module GunFinishesHelper
end

app/helpers/gun_manufacturers_helper.rb
module GunManufacturersHelper
end

app/helpers/guns_helper.rb
module GunsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gun_manufacturers/_form.html.erb
<%= form_for @gunmanufacturer, :html => {:class => "form-horizontal", :role=>"form"} do |f| %>
  <% if @gunmanufacturer.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <h4>Error occured when saving the manufacturer.</h4>

      <ul>
      <% @gunmanufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  	<%= f.label :name, class: "col-sm-2 control-label" %>
  	<div class="col-sm-5">
      <%= f.text_field :name, class: "form-control", :size=>"25", :maxlength=>"25" %>
  	</div>
  </div>
  <div class="form-group">      
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, cols: 20, class: "form-control" %>
    </div>
  </div>
  <div class="btn-group pull-right">
    <%= f.submit :value => "Save", :class => 'btn btn-primary' %>
  	<%= link_to 'Cancel', gun_manufacturers_path, :class => 'btn btn-primary' %>
  </div>      
  
<% end %>

app/views/gun_manufacturers/edit.html.erb
<div class="row">
	<div class="page-header">
      <h4>Edit Manufacturer</h4>
    </div>
</div>

<%= render 'form' %>

app/views/gun_manufacturers/index.html.erb
<div class="row">
  <div class="span12">
    <% content_for :header do  %>
      <p>Header for Gun Manufacturer Here... </p>
    <% end %>

    <div class="page-header">
      <h4>Gun Manufacturer/s</h4>
    </div>

    <% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
    <% end %>

    <div class="table-responsive">
      <table class="table table-brdered table-striped table-hover">
        <tr>
          <th class="col-sm-2"></th>
          <th class="col-sm-5">Name</th>
          <th class="col-sm-5">Description</th>    
        </tr>

      <% @gunmanufacturers.each do |gunmanufacturer| %>
        <tr>
        	<td class="col-sm-2"><%= link_to 'Edit', edit_gun_manufacturer_path(gunmanufacturer) %> <%= link_to 'Destroy', gunmanufacturer, confirm: 'Are you sure you want to delete this category?', method: :delete %></td>
          <td class="col-sm-5"><%= gunmanufacturer.name %></td>
          <td class="col-sm-5"><%= gunmanufacturer.description %></td>    
        </tr>
      <% end %>
      </table>
    </div>

    <br />

    <%= link_to 'New Manufacturer', new_gun_manufacturer_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/gun_manufacturers/new.html.erb
<div class="row">
	<div class="page-header">
      <h4>New Manufacturer</h4>
    </div>
</div>

<%= render 'form' %>