config/routes.rb
JumacV2::Application.routes.draw do

    controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users, :except => [:show]

  get 'users/email_verification/:id' => 'users#email_verification', :as => :verify_email

  resources :roles, :except => [:show]
  resources :gun_categories, :except => [:show], :path => 'guncategories'
  resources :gun_calibers, :except => [:show], :path => 'guncalibers'
  resources :gun_finishes, :except => [:show], :path => 'gunfinishes'
  resources :gun_manufacturers, :except => [:show], :path => 'gunmanufacturers'
  resources :guns

  get "home/index"
  get "home/about"

  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :presence => true, :length => {:minimum => 3}, :uniqueness => true
	validates :email, :presence => true, :uniqueness => true
	validate :email_regex
 
	has_secure_password

	has_one :user_profile, :dependent => :destroy
	accepts_nested_attributes_for :user_profile

	has_many :user_roles, :dependent => :destroy
	has_many :roles, through: :user_roles
	accepts_nested_attributes_for :roles

	def email_regex
    if email.present? and not email.match(/^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i)
      errors.add :email, "This is not a valid email format"
    end

    def is_in_role(rolename)
    	
    end
  end
end

app/controllers/users_controller.rb
require 'securerandom'

class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :get_all_roles, only: [:edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:username)
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_user_profile
  end

  # GET /users/1/edit
  def edit
    
    if !@user.user_profile 
      @user.build_user_profile
    end
    if !@user.roles 
      @user.roles.build
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.verification_code = SecureRandom.base64(10)


    respond_to do |format|
      if @user.save
        UserConfirmationMailer.registration_confirmation(@user).deliver
        format.html { redirect_to users_path, notice: "User #{@user.username} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    set_user

    # @userroles = params["user"]["role_ids"]
    # if !@userroles 
    #   @userroles.each do |role_id|
    #     puts role_id
    #   end
    # end

    if !@user.user_profile 
      @user.build_user_profile
    end    
    respond_to do |format|
      if @user.update(user_params)                
        format.html { redirect_to users_path, notice: "User #{@user.username} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end
  end

  def email_verification

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user 
      @user = User.includes(:user_profile, :roles).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation,
        user_profile_attributes: [:id, :user_id, :last_name, :first_name, :middle_name, 
          :mobile_no, :land_line, :address1, :address2, :city], :role_ids => [])
    end

    def get_all_roles
      @roles = Role.all
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form-horizontal", :role=>"form"} do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <h4>Error occured when saving the user.</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :username, class: "form-control", :size=>"25", :maxlength=>"125" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :email, class: "form-control", :size=>"25", :maxlength=>"250" %>
    </div>
  </div>
  

  <% if editmode %> 
    <div class="row">
      <div class="page-header">
        <h4> User Profile </h4>
      </div>
    </div>

    <%= f.fields_for :user_profile do |p| %>
      <div class="form-group">
        <%= p.label :last_name, 'Last Name', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :last_name, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
      <div class="form-group">
        <%= p.label :first_name, 'First Name', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :first_name, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
      <div class="form-group">
        <%= p.label :middle_name, 'Middle Name', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :middle_name, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
      <div class="form-group">
        <%= p.label :mobile_no, 'Mobile No.', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :mobile_no, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
      <div class="form-group">
        <%= p.label :land_line, 'Telephone No.', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :land_line, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
      <div class="form-group">
        <%= p.label :address1, 'Address', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :address1, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
      <div class="form-group">
        <%= p.label :city, 'City', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= p.text_field :city, class: "form-control", :size=>"25", :maxlength=>"250" %>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="page-header">
        <h4> Member of: </h4>
      </div>
    </div>

    <!-- Check if user is admin -->
    <div class="row">
      <div class="col-md-10 col-md-offset-2">
        <% for role in @roles %>
          <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %> <%= role.name %>
        <% end %> 
      </div>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :password, "Password", class: "col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.password_field :password, class: "form-control", :size=>"25", :maxlength=>"125" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Confirm Password", class: "col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.password_field :password_confirmation, class: "form-control", :size=>"25", :maxlength=>"125" %>
      </div>
    </div>
  <% end %>

  <div class="btn-group pull-right">
    <%= f.submit :value => "Save", :class => 'btn btn-primary' %>
    <% if editmode %>
      <%= link_to 'Back', users_path, :class => 'btn btn-primary' %>
    <% else %> 
      <%= link_to 'Back', home_index_path, :class => 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
	<div class="page-header">
      <h4> My Account </h4>
    </div>
</div>

<%= render :partial => 'form', :locals => { :user => @user, :editmode => true } %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
  <div><%= notice %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
	<div class="page-header">
      <h4> Register </h4>
    </div>
</div>

<%= render :partial => 'form', :locals => { :user => @user, :editmode => false } %>