config/routes.rb
JumacV2::Application.routes.draw do

    controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users, :except => [:show]

  get 'users/email_verification/:id' => 'users#email_verification', :as => :verify_email

  resources :roles, :except => [:show]
  resources :gun_categories, :except => [:show], :path => 'guncategories'
  resources :gun_calibers, :except => [:show], :path => 'guncalibers'
  resources :gun_finishes, :except => [:show], :path => 'gunfinishes'
  resources :gun_manufacturers, :except => [:show], :path => 'gunmanufacturers'
  resources :guns

  get "home/index"
  get "home/about"

  

  root :to => 'home#index'

end

app/models/gun.rb
class Gun < ActiveRecord::Base
	validates :model_name, :presence => true, :length => {:minimum => 3}, :uniqueness => true

	belongs_to :gun_category
	belongs_to :gun_manufacturer

	has_many :gun_available_calibers, :dependent => :destroy
	accepts_nested_attributes_for :gun_available_calibers

	has_many :gun_available_finishes, :dependent => :destroy
	has_many :gun_finishes, through: :gun_available_finishes	
	accepts_nested_attributes_for :gun_finishes
 
	
end

app/models/gun_caliber.rb
class GunCaliber < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }

	has_many :gun_available_calibers, :dependent => :destroy
	accepts_nested_attributes_for :gun_available_calibers
end

app/models/gun_category.rb
class GunCategory < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }

	has_many :guns
end

app/models/gun_finish.rb
class GunFinish < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }

	has_many :gun_available_finishes, :dependent => :destroy
end

app/models/gun_manufacturer.rb
class GunManufacturer < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250, :message => "Please specify the category name." }
	validates :description, :length => { :maximum => 250 }
	
	has_many :guns
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :name, :length => { :minimum => 3, :maximum => 250 }
	validates :description, :length => { :maximum => 250 }

	has_many :user_roles, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :presence => true, :length => {:minimum => 3}, :uniqueness => true
	validates :email, :presence => true, :uniqueness => true
	validate :email_regex
 
	has_secure_password

	has_one :user_profile, :dependent => :destroy
	accepts_nested_attributes_for :user_profile

	has_many :user_roles, :dependent => :destroy
	has_many :roles, through: :user_roles
	accepts_nested_attributes_for :roles

	def email_regex
    if email.present? and not email.match(/^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i)
      errors.add :email, "This is not a valid email format"
    end

    def is_in_role(rolename)
    	
    end
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user	
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/controllers/guns_controller.rb
class GunsController < ApplicationController
  before_action :set_gun, only: [:edit, :update, :destroy]
  before_action :get_all_calibers, only: [:new, :edit]
  before_action :get_all_finishes, only: [:new, :edit]
  before_action :get_all_category, only: [:new, :edit]
  before_action :get_all_manufacturer, only: [:new, :edit]

  def index
    @guns = Gun.all
  end

  def new
    @gun = Gun.new
    # @gun.gun_available_calibers.build 
    @guncalibers = GunCaliber.all
    @guncalibers.each do |gc| 
      @gun.gun_available_calibers.find_or_create_by_gun_caliber_id(:gun_caliber_id => gc.id) {|u| u.is_available}
    end
    @gun.gun_finishes.build 
  end

  def create
    @gun = Gun.new(gun_params)    
    if @gun.save
      redirect_to guns_path, :notice => "Gun #{@gun.model_name} was created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  private
  def set_gun
    @gun = Gun.include(:gun_calibers, :gun_finishes).find(params[:id])
  end

  def gun_params
    params.require(:gun).permit(:model_name, :short_desc, :long_desc, :gun_category_id, :gun_manufacturer_id,       
      :gun_finish_ids, 
      :gun_available_calibers_attributes => [:id, :gun_caliber_id, :round_capacity, :is_available] 
      )
  end

  def get_all_calibers
    @guncalibers = GunCaliber.all
  end

  def get_all_finishes 
    @gunfinishes = GunFinish.all
  end

  def get_all_category
    @guncategory = GunCategory.all
  end

  def get_all_manufacturer
    @gunmanufacturer = GunManufacturer.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gun_caliber_helper.rb
module GunCaliberHelper
end

app/helpers/gun_category_helper.rb
module GunCategoryHelper
end

app/helpers/gun_finishes_helper.rb
module GunFinishesHelper
end

app/helpers/guns_helper.rb
module GunsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login.html.erb
<% if session[:user_id] %>
	<ul class="nav navbar-nav navbar-right">
		<li>
			<p class="navbar-text">Welcome, <%= link_to @username, edit_user_path(session[:user_id]) %> , <%= link_to 'Log out', logout_path, method: :delete, :class=>"btn btn-success" %>
			</p> 
		</li>
	</ul>
<% else %>
	<%= form_tag({:action => 'create', :controller => 'sessions'}, {:class => 'navbar-form navbar-right', :role=> 'search'}) do %>
		<div class="form-group">
			<%= text_field_tag :username, params[:username], :class=>"form-control", :placeholder=>"Username" %>
		</div>
		<div class="form-group">
			<%= password_field_tag :password, params[:password],  :class=>"form-control", :placeholder=>"Password" %>
		</div>
		<%= submit_tag "Login", :class=>"btn btn-primary" %>	
		<%= link_to "Register", new_user_path, :class => 'btn btn-primary' %>	
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JumacV2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- [if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![end]-->
</head>
<body>

  <!-- Start: Navigation wrapper -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">            
        <!-- Below button used for responsive navigation -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="index.html" class="navbar-brand brand-bootbus">Bootbusiness</a>
      </div>  
        <!-- Start: Primary navigation -->
      <div class="navbar-collapse collapse">        
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
            <ul class="dropdown-menu">                                          
              <li>
				        <%= link_to 'Roles', roles_path %>
			        </li>
              <li>
                <%= link_to 'Users', users_path %>
              </li>
              <li class="divider"></li>
              <li><a href="service.html">Service3</a></li>
              <li><a href="all_services.html">All services</a></li>
            </ul>                  
          </li>                
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Maintenance<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Category', gun_categories_path %>
              </li>
              <li>
                <%= link_to 'Caliber', gun_calibers_path %>
              </li>
              <li>
                <%= link_to 'Finish', gun_finishes_path %>
              </li>
              <li>
                <%= link_to 'Manufacturer', gun_manufacturers_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Guns', guns_path %>
              </li>
            </ul>
          </li>           
          <li><a href="contact_us.html">Contact us</a></li>           
        </ul>        
        <%= render :partial => 'layouts/login' %>
      </div>
      
    </div>
  </div>
  <!-- End: Navigation wrapper -->   


	<div class="container">
		<%= yield %>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="span2">
            <h4><i class="icon-star icon-white"></i> Products</h4>
            <nav>
              <ul class="quick-links">
                <li><a href="product.html">Product1</a></li>
                <li><a href="product.html">Product2</a></li>
                <li><a href="product.html">Product3</a></li>
                <li><a href="all_products.html">All products</a></li>
              </ul>
            </nav>
            <h4><i class="icon-cogs icon-white"></i> Services</h4>
            <nav>
              <ul class="quick-links">
                <li><a href="service.html">Service1</a></li>
                <li><a href="service.html">Service2</a></li>
                <li><a href="service.html">Service3</a></li>
                <li><a href="all_services.html">All services</a></li>              
              </ul>
            </nav>
          </div>
          <div class="span2">
            <h4><i class="icon-beaker icon-white"></i> About</h4>
            <nav>
              <ul class="quick-links">
                <li><a href="our_works.html">Our works</a></li>
                <li><a href="patnerships.html">Patnerships</a></li>
                <li><a href="leadership.html">Leadership</a></li>
                <li><a href="news.html">News</a></li>
                <li><a href="events.html">Events</a></li>
                <li><a href="blog.html">Blog</a></li>
              <ul>
            </nav>          
          </div>
          <div class="span2">
            <h4><i class="icon-thumbs-up icon-white"></i> Support</h4>
            <nav>
              <ul class="quick-links">
                <li><a href="faq.html">FAQ</a></li>
                <li><a href="contact_us.html">Contact us</a></li>            
              </ul>
            </nav>
            <h4><i class="icon-legal icon-white"></i> Legal</h4>
            <nav>
              <ul class="quick-links">
                <li><a href="#">License</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Security</a></li>      
              </ul>
            </nav>            
          </div>
          <div class="span3">
            <h4>Get in touch</h4>
            <div class="social-icons-row">
              <a href="#"><i class="icon-twitter"></i></a>
              <a href="#"><i class="icon-facebook"></i></a>
              <a href="#"><i class="icon-linkedin"></i></a>                                         
            </div>
            <div class="social-icons-row">
              <a href="#"><i class="icon-google-plus"></i></a>              
              <a href="#"><i class="icon-github"></i></a>
              <a href="mailto:soundar.rathinasamy@gmail.com"><i class="icon-envelope"></i></a>        
            </div>
            <div class="social-icons-row">
              <i class="icon-phone icon-large phone-number"></i> +919750227877
            </div>
          </div>      
          <div class="span3">
            <h4>Get updated by email</h4>
            <form>
              <input type="text" name="email" placeholder="Email address">
              <input type="submit" class="btn btn-primary" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
      <hr class="footer-divider">
      <div class="container">
        <p>
          &copy; 2012-3000 Bootbusiness, Inc. All Rights Reserved.
        </p>
      </div>
    </footer>
   </div>
</body>
</html>